import type { Meta, StoryObj } from '@storybook/react';
import { CellType } from 'src/features/simulation/types/CellType';
import { CellSet } from './CellSet';

const meta = {
    title: 'CellSet',
    component: CellSet,
} satisfies Meta<typeof CellSet>;

export default meta;

type Story = StoryObj<typeof CellSet>;

export const Simple: Story = {
    args: {
        columns: 9,
        cells: [
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.SolidWall },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace, antColor: 'red' },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.UndergroundSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace, antColor: 'blue' },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
            { cellType: CellType.OutdoorSpace },
        ],
    }
}
